version: '3'

services:
  backend-core:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-core
    restart: always
    volumes:
      - ./backend/:/code/
    depends_on:
      - redis
    ports:
      - 5050:5050
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - backend
    
  flower:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: flower
    restart: always
    volumes:
      - ./backend/:/code/
    depends_on:
      - redis
    ports:
      - 5555:5555

  marqo:
    container_name: marqo
    privileged: true
    ports:
        - '8882:8882'
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    image: 'marqoai/marqo:latest'
    volumes:
      - ./backend/:/marqo/
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

networks:
  backend:
    driver: bridge